# Generated by Django 6.0.6 on 2026-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectattachment",
            name="file",
            field=models.FileField(upload_to="project_attachments/"),
        ),
    ]
